### ISSUE TITLE
Search and BIN happen only once and doesn't trigerred anymore

### ISSUE THREAD

**Issue by miko8x** [oRastor/fut20-web-app#12]
Hi,

Thank you very much for this addon!
It looks great and very nice to use.
From some reason I can only get the search running once (maybe that is by design)
I just don't see any new attempts on the debug window

I'm using Chrome latest version

Thanks

**Comment by Mit010** [comment]
your wait time is probably not set up right. Put it on "1-5"

**Comment by miko8x** [comment]
Thanks for replying!
Just tried it but it's the same behaviour
