### ISSUE TITLE
Same auctions

### ISSUE THREAD

**Issue by Verdagen** [oRastor/fut20-web-app#2]
Hello,
Can you do something about recurring auctions? I manually get rid of it through change minimalBID price(150,200,250... -this does not change the search results, but removes duplicate auctions). Can it be implemented somehow in the script? Maybe you have another way to do it?
cheers

**Comment by oRastor** [comment]
Hi, I cannot understand what do you mean. Can you explain your problem with steps and examples?

**Comment by Verdagen** [comment]
I will try to explain it more precisely.
1. I search for auctions.
2. I find a card with id example [256631278515] and buy it.
3. I am looking again.
4. A card with the same id [256631278515] is still on the market and I'm trying to buy it - this causes a buy error.
5. Every time I search, I try to buy it again.
6. After a few mistakes in purchase, it disappears from the market.

You can get rid of it by changing MIN BID example 150, 200, 250... after each purchase attempt.

Do you understand what I mean?

**Comment by oRastor** [comment]
Oh, ok. I will think about this. Maybe changing of MIN BID is not the best idea because one time you will want to buy a player with max price value 750. And for this situation your min bid allowed values to recurrence change are only: 150, 200, 250...

**Comment by oRastor** [comment]
It can be cache on the client side.

**Comment by Verdagen** [comment]
> 
> 
> Oh, ok. I will think about this. Maybe changing of MIN BID is not the best idea because one time you will want to buy a player with max price value 750. And for this situation your min bid allowed values to recurrence change are only: 150, 200, 250...

Yeah, I know it's not the best idea. But it doesn't affect the cards I search.

Thank you for your answer. ;-)

**Comment by yhanssens** [comment]
I ran into the same issue. My fix was to store the ids of the items in an array and filter those ids out of the following search results.

**Comment by Verdagen** [comment]
I'm not sure, but changing the max buy now price works the same.

**Comment by Verdagen** [comment]
> I ran into the same issue. My fix was to store the ids of the items in an array and filter those ids out of the following search results.

Well thought out. Can you publish the version with this patch?

**Comment by LaKo13** [comment]
Will filtering them out actually solve this for the search or only for the
autobuyer? Seems like it only solves it optically and not from the actual
filter aspect. Can't filter out IDs on the actual app.

**Comment by yhanssens** [comment]
@LaKo13 It only solves the autobuyer making unnecessary buy requests, don't want that 429 ;) Don't think there's anything you can do to actually fix the search results because this issue is also on console when using the 'normal' transfer market.

**Comment by LaKo13** [comment]
@yhanssens that makes perfect sense. Awesome solution. Mind sharing it?

**Comment by d235** [comment]
yes i like your work- but changing the max bid steps +3 and -3 would fix the problem and the searches would be more effective --> i think it will create a new "real"  request

**Comment by oRastor** [comment]
I will work with this problem after EA open transfers for my account...

**Comment by oRastor** [comment]
Now please use autobuyer with not competitive search setup

**Comment by mehrdadie** [comment]
> Now please use autobuyer with not competitive search setup

Hey man, thanks a lot for your time and effort, what does it mean competitive search setup?

**Comment by oRastor** [comment]
I mean, that more popular player trying to buy at the same time more likely. So you must find not so popular player where you be only one who uses autobuyer or other software or in-game rapid search.

**Comment by boefiee** [comment]
The autobuyer is not working properly at all.
Whenever i am searching on a diffrent account with the ps4 for the same player/item, loads of cards pop up.
Nothing pops up with the autobuyer, maybe 1 in 5/10 minutes...

Also many fails and cards with same ID.
Last year it worked great and i really apreciate the work and effort, but this year it seems a little rusty and not working normaly.
Hope someone can make some changes and updates and let us enjoy this great autobuyer once again.

Thanks !

**Comment by BzRk88** [comment]
Same here. Hope you Guys van help us out. And make the autobuyer great again.

**Comment by TiebeVercoutter** [comment]
The autobuyer only searches every 5 secs at max. When snipping on console you will search about every 2 seconds. Also don’t use te autobuyer on popular players, there is the chance that maybe 2 other autobuyers are sniping the same player. Work has to been done but you can already make some nice coins with this script.

**Comment by boefiee** [comment]
> The autobuyer only searches every 5 secs at max. When snipping on console you will search about every 2 seconds. Also don’t use te autobuyer on popular players, there is the chance that maybe 2 other autobuyers are sniping the same player. Work has to been done but you can already make some nice coins with this script.

I think you dont even have a clue how this autobuyer and sniping works to be honest.
200 cards pops up on ps4 in 10 minutes on a specific sniping filter like position change cards.
only 5 or 10 popping up on the autobuyer.
ALSO NO BUY FAILS which means he AT LEAST finds the card, but no the autobuyer doesnt find anything.
Dont get me wrong i apreciate the great coding and development of the autobuyer because me myself i dont have a clue how to code, but there is a lot of work to be done before this autobuyer is finished and i hope it gets fixed soon.
,.

**Comment by boefiee** [comment]
https://imgur.com/a/xV0Trpc

**Comment by oRastor** [comment]
Please try my fix, have not tested yet. Because EA did not open transfers for my web app for today.

**Comment by Verdagen** [comment]
> 
> 
> > The autobuyer only searches every 5 secs at max. When snipping on console you will search about every 2 seconds. Also don’t use te autobuyer on popular players, there is the chance that maybe 2 other autobuyers are sniping the same player. Work has to been done but you can already make some nice coins with this script.
> 
> I think you dont even have a clue how this autobuyer and sniping works to be honest.
> 200 cards pops up on ps4 in 10 minutes on a specific sniping filter like position change cards.
> only 5 or 10 popping up on the autobuyer.
> ALSO NO BUY FAILS which means he AT LEAST finds the card, but no the autobuyer doesnt find anything.
> Dont get me wrong i apreciate the great coding and development of the autobuyer because me myself i dont have a clue how to code, but there is a lot of work to be done before this autobuyer is finished and i hope it gets fixed soon.
> ,.
a profit of 2 million in a week is a poor result of autobuyer?

**Comment by Verdagen** [comment]
> 
> 
> Please try my fix, have not tested yet. Because EA did not open transfers for my web app for today.

Looks very good at the moment. There is no error after purchase. Thanks for the update!

**Comment by TiebeVercoutter** [comment]
> > The autobuyer only searches every 5 secs at max. When snipping on console you will search about every 2 seconds. Also don’t use te autobuyer on popular players, there is the chance that maybe 2 other autobuyers are sniping the same player. Work has to been done but you can already make some nice coins with this script.
> 
> I think you dont even have a clue how this autobuyer and sniping works to be honest.
> 200 cards pops up on ps4 in 10 minutes on a specific sniping filter like position change cards.
> only 5 or 10 popping up on the autobuyer.
> ALSO NO BUY FAILS which means he AT LEAST finds the card, but no the autobuyer doesnt find anything.
> Dont get me wrong i apreciate the great coding and development of the autobuyer because me myself i dont have a clue how to code, but there is a lot of work to be done before this autobuyer is finished and i hope it gets fixed soon.
> ,.

I know perfectly what snipping is, have done it the past fifa’s to make my coins. A position changing card is a popular filter. I personally think that by making the autobuyer search more the risk in banning increases. Also it is a autobuyer not a autosniper keer that in mind.

**Comment by TiebeVercoutter** [comment]
> Please try my fix, have not tested yet. Because EA did not open transfers for my web app for today.

They open the transfermarket after you played about 30 matches in fut. Thanks for the update by the way

**Comment by Verdagen** [comment]
20 minutes on the market and no mistakes, although many purchases. Well done work.

**Comment by oRastor** [comment]
> > Please try my fix, have not tested yet. Because EA did not open transfers for my web app for today.
> 
> Looks very good at the moment. There is no error after purchase. Thanks for the update!
> 
> Can we know what you did?

After buy request, I add an auction identity of item to list. And next time before making a new buy request I check it on this list. If it already exists I do not make buy request.

The max size of this list is 300 items.

**Comment by BzRk88** [comment]
Great work! Now find a good filter lol. Thanx for your work

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: Orest Budzhak <notifications@github.com>
Verzonden: Friday, October 4, 2019 9:39:05 AM
Aan: oRastor/fut20-web-app <fut20-web-app@noreply.github.com>
CC: BzRk88 <hendriks_jimmy@hotmail.com>; Comment <comment@noreply.github.com>
Onderwerp: Re: [oRastor/fut20-web-app] Same auctions (#2)


Please try my fix, have not tested yet. Because EA did not open transfers for my web app for today.

Looks very good at the moment. There is no error after purchase. Thanks for the update!

Can we know what you did?

After buy request, I add an auction identity of item to list. And next time before making a new buy request I check it on this list. If it already exists I do not make buy request.

The max size of this list is 300 items.

**Comment by oRastor** [comment]
Update one more time, please. Fix bug with the wrong buy count decrementing when the buy request not send.

**Comment by Mit010** [comment]
@Verdagen any tips on filters? players? way to look for profitable buys?
