### ISSUE TITLE
Permanently banned because of update.

### ISSUE THREAD

**Issue by Redaa91** [oRastor/fut20-web-app#20]
Hi @oRastor,
Since yesterday when the search and statistics bar are gone + coins my accounts are permantly banned by EA.
I got mails from EA saying that botting is not allowed blabla.
I know this happened because of update and because of the autobuyer is not the same anymore, i had this weird feeling last night.
Please fix this autobuyer as soon as possible otherwise many many people will get banned.

**Comment by oRastor** [comment]
clone #19
