### ISSUE TITLE
No autolist

### ISSUE THREAD

**Issue by TiebeVercoutter** [oRastor/fut20-web-app#3]
Would it be possible to add a switch in the menu which allows you to keep a player and not autolist it?

ps: absolutely love the way this works (I sometimes get a softban of like an hour, is this fixable by increasing waiting time?)

**Comment by oRastor** [comment]
Hi, just put "0" into sell prize field.

**Comment by TiebeVercoutter** [comment]
Ohw haha okay thanks didn’t know that
