### ISSUE TITLE
not working fifa19 autobuyer was better.

### ISSUE THREAD

**Issue by boefiee** [oRastor/fut20-web-app#5]
The autobuyer is not working properly at all.
Whenever i am searching on a diffrent account with the ps4 for the same player/item, loads of cards pop up.
Nothing pops up with the autobuyer, maybe 1 in 5/10 minutes...

Also many fails and cards with same ID.
Last year it worked great and i really apreciate the work and effort, but this year it seems a little rusty and not working normaly.
Hope someone can make some changes and updates and let us enjoy this great autobuyer once again.

Thanks !

**Comment by oRastor** [comment]
Not an issue.
